# Generated by Django 6.0.6 on 2026-06-16 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutricionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia')),
                ('especialidad', models.CharField(blank=True, choices=[('clinica', 'Nutricion clinica'), ('deportiva', 'Nutricion deportiva'), ('infantil', 'Nutricion infantil'), ('embarazo', 'Embarazo y lactancia'), ('vegana', 'Vegetarianismo y veganismo'), ('diabetes', 'Diabetes'), ('tca', 'Trastornos de la conducta alimentaria'), ('obesidad', 'Obesidad'), ('otra', 'Otra')], max_length=20, verbose_name='Especialidad')),
                ('matricula', models.CharField(max_length=50, verbose_name='Matricula')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('edades_atendidas', models.CharField(blank=True, help_text='Separadas por coma. Opciones: ninos, adolescentes, adultos, mayores', max_length=200, verbose_name='Edades que atiende')),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('ambas', 'Presencial y virtual')], default='ambas', max_length=20, verbose_name='Modalidad')),
                ('acepta_obras_sociales', models.BooleanField(default=False, verbose_name='Acepta obras sociales')),
                ('obras_sociales_detalle', models.TextField(blank=True, help_text='Listado de obras sociales que acepta', verbose_name='Detalle de obras sociales')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutricionista', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutricionista',
                'verbose_name_plural': 'Nutricionistas',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='core.nutricionista')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField(verbose_name='Inicio')),
                ('duracion_minutos', models.PositiveIntegerField(default=60, verbose_name='Duracion (min)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('realizado', 'Realizado')], default='pendiente', max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='core.nutricionista')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha_hora_inicio'],
            },
        ),
    ]
