# Generated by Django 6.0.6 on 2026-06-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Obra social',
                'verbose_name_plural': 'Obras sociales',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='nutricionista',
            name='acepta_obras_sociales',
        ),
        migrations.RemoveField(
            model_name='nutricionista',
            name='obras_sociales_detalle',
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Destacado en home'),
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='foto',
            field=models.FileField(blank=True, help_text='Subir foto en JPG o PNG', null=True, upload_to='nutricionistas/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='edades_atendidas',
            field=models.CharField(blank=True, help_text='Separadas por coma: ninos, adolescentes, adultos, mayores', max_length=200, verbose_name='Edades que atiende'),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='modalidad',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('online', 'Online'), ('ambas', 'Virtual y Online')], default='ambas', max_length=20, verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='obras_sociales',
            field=models.ManyToManyField(blank=True, to='core.obrasocial', verbose_name='Obras sociales que acepta'),
        ),
    ]
