# Generated by Django 6.0.6 on 2026-06-17 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_obrasocial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='nutricionista',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='especialidades',
            field=models.CharField(blank=True, help_text='Separadas por coma. Ejemplo: clinica,deportiva', max_length=200, verbose_name='Especialidades'),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='edades_atendidas',
            field=models.CharField(blank=True, help_text='Separadas por coma. Opciones: ninos, adolescentes, adultos, mayores', max_length=200, verbose_name='Edades que atiende'),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='nutricionistas/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('ambas', 'Presencial y virtual')], default='ambas', max_length=20, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='obras_sociales',
            field=models.ManyToManyField(blank=True, to='core.obrasocial', verbose_name='Obras sociales'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=60, verbose_name='Duracion (minutos)'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('realizado', 'Realizado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_hora_inicio',
            field=models.DateTimeField(verbose_name='Fecha y hora de inicio'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ciudad', verbose_name='Ciudad'),
        ),
    ]
