# Generated by Django 6.0.6 on 2026-06-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ciudad_remove_nutricionista_especialidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoInteresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('plan_interes', models.CharField(choices=[('publicidad', 'Solo publicidad (perfil en web e Instagram)'), ('herramientas', 'Publicidad + Herramientas (turnero, pacientes, etc.)'), ('sin_definir', 'Todavia no lo decidi')], default='sin_definir', max_length=20, verbose_name='Plan de interes')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contactado', models.BooleanField(default=False, verbose_name='Contactado')),
            ],
            options={
                'verbose_name': 'Contacto interesado',
                'verbose_name_plural': 'Contactos interesados',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='tipo',
            field=models.CharField(choices=[('base', 'Solo publicidad'), ('premium', 'Publicidad + Herramientas')], default='premium', help_text='Base = solo perfil publico. Premium = perfil + dashboard.', max_length=10, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='aprobado',
            field=models.BooleanField(default=False, verbose_name='Aprobado / Activo'),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='edades_atendidas',
            field=models.CharField(blank=True, max_length=200, verbose_name='Edades que atiende'),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='especialidades',
            field=models.CharField(blank=True, help_text='CSV: clinica,deportiva', max_length=200, verbose_name='Especialidades'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=60, verbose_name='Duracion (min)'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_hora_inicio',
            field=models.DateTimeField(verbose_name='Fecha y hora'),
        ),
    ]
