# Generated by Django 6.0.6 on 2026-06-18 01:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactointeresado_nutricionista_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='actividad_fisica_frecuencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Frecuencia / duracion'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='actividad_fisica_tipo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de actividad fisica'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='agua_diaria_litros',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Agua diaria (litros)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, verbose_name='Alergias e intolerancias alimentarias'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='antecedentes_familiares',
            field=models.TextField(blank=True, verbose_name='Antecedentes familiares relevantes'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cirugias_previas',
            field=models.TextField(blank=True, verbose_name='Cirugias previas'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='comidas_por_dia',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Comidas por dia'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='consume_alcohol',
            field=models.CharField(blank=True, choices=[('no', 'No consume'), ('ocasional', 'Ocasional'), ('frecuente', 'Frecuente')], max_length=20, verbose_name='Consumo de alcohol'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='consume_tabaco',
            field=models.BooleanField(default=False, verbose_name='Consume tabaco'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='derivado_por_medico',
            field=models.BooleanField(default=False, verbose_name='Derivado por medico'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='dni',
            field=models.CharField(blank=True, max_length=20, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermedades',
            field=models.TextField(blank=True, help_text='Diabetes, hipertension, celiaquía, hipotiroidismo, etc.', verbose_name='Enfermedades diagnosticadas'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='horas_sueno',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Horas de sueno'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicacion_actual',
            field=models.TextField(blank=True, verbose_name='Medicacion actual'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nivel_estres',
            field=models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('moderado', 'Moderado'), ('alto', 'Alto'), ('muy_alto', 'Muy alto')], max_length=20, verbose_name='Nivel de estres'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre_medico',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del medico'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('perdida_peso', 'Perdida de peso'), ('ganancia_muscular', 'Ganancia de masa muscular'), ('control_enfermedad', 'Control de enfermedad'), ('rendimiento', 'Rendimiento deportivo'), ('embarazo', 'Embarazo / Lactancia'), ('habitos', 'Habitos saludables'), ('otro', 'Otro')], max_length=30, verbose_name='Objetivo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='objetivo_detalle',
            field=models.TextField(blank=True, verbose_name='Detalle del objetivo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='obra_social',
            field=models.CharField(blank=True, max_length=100, verbose_name='Obra social / prepaga'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro / Prefiero no decir')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactointeresado',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactointeresado',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactointeresado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactointeresado',
            name='plan_interes',
            field=models.CharField(choices=[('publicidad', 'Solo publicidad'), ('herramientas', 'Publicidad + Herramientas'), ('sin_definir', 'Todavia no lo decidi')], default='sin_definir', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactointeresado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ciudad'),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='edades_atendidas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='especialidades',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='nutricionistas/'),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='matricula',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('ambas', 'Presencial y virtual')], default='ambas', max_length=20),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='obras_sociales',
            field=models.ManyToManyField(blank=True, to='core.obrasocial'),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='tipo',
            field=models.CharField(choices=[('base', 'Solo publicidad'), ('premium', 'Publicidad + Herramientas')], default='premium', max_length=10, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='obrasocial',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='obrasocial',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('realizado', 'Realizado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='turno',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de la consulta')),
                ('peso_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso del dia (kg)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones / Evolucion')),
                ('cambios_al_plan', models.TextField(blank=True, verbose_name='Cambios al plan')),
                ('proximo_turno', models.DateField(blank=True, null=True, verbose_name='Proximo turno')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha del analisis')),
                ('glucemia', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Glucemia (mg/dL)')),
                ('colesterol_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Colesterol total (mg/dL)')),
                ('colesterol_hdl', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Colesterol HDL (mg/dL)')),
                ('colesterol_ldl', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Colesterol LDL (mg/dL)')),
                ('trigliceridos', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Trigliceridos (mg/dL)')),
                ('hemoglobina', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hemoglobina (g/dL)')),
                ('ferritina', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ferritina (ng/mL)')),
                ('vitamina_d', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Vitamina D (ng/mL)')),
                ('tsh', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='TSH (mUI/L)')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='laboratorios/', verbose_name='Archivo PDF')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratorios', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('altura_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Altura (cm)')),
                ('pct_grasa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% Grasa corporal')),
                ('pct_musculo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% Masa muscular')),
                ('cintura_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Cintura (cm)')),
                ('cadera_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Cadera (cm)')),
                ('pliegues', models.TextField(blank=True, verbose_name='Pliegues cutaneos')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Medicion',
                'verbose_name_plural': 'Mediciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PlanAlimentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha del plan')),
                ('calorias_objetivo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calorias objetivo (kcal)')),
                ('pct_proteinas', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Proteinas (%)')),
                ('pct_carbohidratos', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Carbohidratos (%)')),
                ('pct_grasas', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Grasas (%)')),
                ('plan_semanal', models.TextField(blank=True, verbose_name='Plan semanal (descripcion)')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='planes/', verbose_name='Plan en PDF')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Plan alimentario',
                'verbose_name_plural': 'Planes alimentarios',
                'ordering': ['-fecha'],
            },
        ),
    ]
