# Generated by Django 6.0.6 on 2026-06-19 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_nutricionista_acepta_obras_sociales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obrasocial',
            options={'ordering': ['nombre'], 'verbose_name': 'Obra Social', 'verbose_name_plural': 'Obras Sociales'},
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='contactointeresado',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='contactointeresado',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactointeresado',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contactointeresado',
            name='plan_interes',
            field=models.CharField(choices=[('publicidad', 'Solo publicidad (perfil en web e Instagram)'), ('herramientas', 'Publicidad + Herramientas (turnero, pacientes, etc.)'), ('sin_definir', 'Todavia no lo decidi')], default='sin_definir', max_length=20, verbose_name='Plan de interes'),
        ),
        migrations.AlterField(
            model_name='contactointeresado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='pliegues',
            field=models.TextField(blank=True, verbose_name='Notas pliegues'),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='edades_atendidas',
            field=models.CharField(blank=True, help_text='Separadas por coma. Opciones: ninos, adolescentes, adultos, mayores', max_length=200, verbose_name='Edades que atiende'),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='especialidades',
            field=models.CharField(blank=True, help_text='Separadas por coma. Ejemplo: clinica,deportiva', max_length=200),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='matricula',
            field=models.CharField(max_length=50, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('ambas', 'Presencial y virtual')], default='ambas', max_length=20, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='obras_sociales',
            field=models.ManyToManyField(blank=True, to='core.obrasocial', verbose_name='Obras sociales'),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='tipo',
            field=models.CharField(choices=[('base', 'Solo publicidad'), ('premium', 'Publicidad + Herramientas')], default='premium', help_text='Base = solo perfil publico. Premium = perfil + dashboard.', max_length=10, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='enfermedades',
            field=models.TextField(blank=True, verbose_name='Enfermedades preexistentes'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nivel_estres',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nivel de estres percibido'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('bajar_peso', 'Bajar de peso'), ('subir_peso', 'Subir de peso'), ('ganar_musculo', 'Ganar masa muscular'), ('mantener', 'Mantener peso actual'), ('rendimiento', 'Mejorar rendimiento deportivo'), ('salud', 'Mejorar salud general'), ('otro', 'Otro')], max_length=20, verbose_name='Objetivo principal'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.obrasocial', verbose_name='Obra social'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('otro', 'Otro / Prefiero no decir')], max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=60, verbose_name='Duracion (minutos)'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('realizado', 'Realizado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_hora_inicio',
            field=models.DateTimeField(verbose_name='Fecha y hora de inicio'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo'),
        ),
    ]
