# Generated by Django 5.2.15 on 2026-07-02 00:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


def poblar_tokens(apps, schema_editor):
    """
    Asigna un token unico a cada turno existente.
    Nota: se recorren TODOS los turnos porque en el AddField SQLite evalua
    el default una sola vez y deja el mismo UUID repetido en todas las filas.
    """
    Turno = apps.get_model('core', 'Turno')
    for turno in Turno.objects.all():
        turno.token = uuid.uuid4()
        turno.save(update_fields=['token'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pais_ciudad_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='apellido_contacto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido (reserva online)'),
        ),
        migrations.AddField(
            model_name='turno',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email (reserva online)'),
        ),
        migrations.AddField(
            model_name='turno',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID de pago MP'),
        ),
        migrations.AddField(
            model_name='turno',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID de preferencia MP'),
        ),
        migrations.AddField(
            model_name='turno',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre (reserva online)'),
        ),
        migrations.AddField(
            model_name='turno',
            name='origen',
            field=models.CharField(choices=[('manual', 'Cargado por el nutricionista'), ('online', 'Reservado online por el paciente')], default='manual', max_length=10, verbose_name='Origen'),
        ),
        migrations.AddField(
            model_name='turno',
            name='recordatorio_enviado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recordatorio de seña enviado'),
        ),
        migrations.AddField(
            model_name='turno',
            name='sena_monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto de la seña'),
        ),
        migrations.AddField(
            model_name='turno',
            name='sena_pagada',
            field=models.BooleanField(default=False, verbose_name='Seña pagada'),
        ),
        migrations.AddField(
            model_name='turno',
            name='sena_pagada_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago de la seña'),
        ),
        migrations.AddField(
            model_name='turno',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefono (reserva online)'),
        ),
        migrations.AddField(
            model_name='turno',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token para que el paciente gestione su turno sin login', null=True),
        ),
        migrations.RunPython(poblar_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='turno',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token para que el paciente gestione su turno sin login', unique=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pendiente_sena', 'Esperando seña'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido (seña impaga)'), ('realizado', 'Realizado'), ('no_asistio', 'No asistió')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='ConfiguracionTurnero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False, help_text='Si esta activo, los pacientes pueden reservar desde tu link publico.', verbose_name='Turnero online activo')),
                ('duracion_turno_minutos', models.PositiveIntegerField(default=30, verbose_name='Duracion de cada turno (minutos)')),
                ('anticipacion_maxima_dias', models.PositiveIntegerField(default=30, verbose_name='Hasta cuantos dias hacia adelante se puede reservar')),
                ('anticipacion_minima_horas', models.PositiveIntegerField(default=3, verbose_name='Anticipacion minima para reservar (horas)')),
                ('requiere_sena', models.BooleanField(default=True, verbose_name='Pedir seña para confirmar el turno')),
                ('precio_consulta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de la consulta ($)')),
                ('porcentaje_sena', models.PositiveIntegerField(default=50, verbose_name='Porcentaje de seña (%)')),
                ('horas_recordatorio', models.PositiveIntegerField(default=24, verbose_name='Enviar recordatorio con link de pago (horas antes)')),
                ('horas_limite_pago', models.PositiveIntegerField(default=6, verbose_name='Si no paga, liberar el turno (horas antes)')),
                ('mp_user_id', models.CharField(blank=True, max_length=50, verbose_name='MP User ID')),
                ('mp_access_token', models.CharField(blank=True, max_length=200)),
                ('mp_refresh_token', models.CharField(blank=True, max_length=200)),
                ('mp_public_key', models.CharField(blank=True, max_length=200)),
                ('mp_token_expira_en', models.DateTimeField(blank=True, null=True)),
                ('mp_conectado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nutricionista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='turnero', to='core.nutricionista')),
            ],
            options={
                'verbose_name': 'Configuracion de turnero',
                'verbose_name_plural': 'Configuraciones de turnero',
            },
        ),
        migrations.CreateModel(
            name='BloqueoFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField(verbose_name='Desde')),
                ('fecha_hasta', models.DateField(verbose_name='Hasta')),
                ('motivo', models.CharField(blank=True, max_length=100, verbose_name='Motivo')),
                ('turnero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='core.configuracionturnero')),
            ],
            options={
                'verbose_name': 'Fecha bloqueada',
                'verbose_name_plural': 'Fechas bloqueadas',
                'ordering': ['fecha_desde'],
            },
        ),
        migrations.CreateModel(
            name='FranjaHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')], verbose_name='Dia')),
                ('hora_inicio', models.TimeField(verbose_name='Desde')),
                ('hora_fin', models.TimeField(verbose_name='Hasta')),
                ('turnero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franjas', to='core.configuracionturnero')),
            ],
            options={
                'verbose_name': 'Franja horaria',
                'verbose_name_plural': 'Franjas horarias',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
