# Generated by Django 6.0.6 on 2026-07-09 00:56

import core.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_turnero_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del archivo')),
                ('archivo', models.FileField(upload_to='archivos_pacientes/', validators=[core.models.validar_tamano_archivo], verbose_name='Archivo')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
