# Generated by Django 6.0.6 on 2026-07-10 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_archivo_seguridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactointeresado',
            name='pais',
            field=models.ForeignKey(blank=True, help_text='Determina qué link de Mercado Pago y qué precio recibe en el mail de planes.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pais', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='pais',
            field=models.ForeignKey(blank=True, help_text='Se elige en el registro. Determina el plan/precio de suscripción que se le ofrece.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pais', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='pais',
            name='mp_link_basico',
            field=models.URLField(blank=True, help_text='Link de suscripción de Mercado Pago del Plan Básico para este país.', verbose_name='Link MP — Plan Básico'),
        ),
        migrations.AddField(
            model_name='pais',
            name='mp_link_premium',
            field=models.URLField(blank=True, help_text='Link de suscripción de Mercado Pago del Plan Completo para este país.', verbose_name='Link MP — Plan Completo'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='activo',
            field=models.BooleanField(default=True, help_text='Solo los países activos aparecen para elegir en el registro y en "Quiero ser parte".', verbose_name='Activo'),
        ),
    ]
