# Generated by Django 6.0.6 on 2026-07-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contactointeresado_pais_nutricionista_pais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='mp_link_basico_trimestral',
            field=models.URLField(blank=True, help_text='Link de suscripción de Mercado Pago del Plan Básico, facturación trimestral.', verbose_name='Link MP — Básico trimestral'),
        ),
        migrations.AddField(
            model_name='pais',
            name='mp_link_premium_trimestral',
            field=models.URLField(blank=True, help_text='Link de suscripción de Mercado Pago del Plan Completo, facturación trimestral.', verbose_name='Link MP — Completo trimestral'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='mp_link_basico',
            field=models.URLField(blank=True, help_text='Link de suscripción de Mercado Pago del Plan Básico, facturación mensual.', verbose_name='Link MP — Básico mensual'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='mp_link_premium',
            field=models.URLField(blank=True, help_text='Link de suscripción de Mercado Pago del Plan Completo, facturación mensual.', verbose_name='Link MP — Completo mensual'),
        ),
    ]
