# Generated by Django 6.0.6 on 2026-07-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pais_mp_link_basico_trimestral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricionista',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, help_text='Se completa sola la primera vez que se tilda "Aprobado". No se pisa después.', null=True, verbose_name='Fecha de aprobación'),
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='frecuencia_pago',
            field=models.CharField(blank=True, choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral')], help_text='Con qué link de Mercado Pago se suscribió — elegilo ANTES de tildar "Aprobado" la primera vez, así se calcula bien la próxima fecha de revisión.', max_length=10, verbose_name='Frecuencia de pago'),
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='proxima_revision_pago',
            field=models.DateField(blank=True, help_text='Cuando confirmes en Mercado Pago que renovó, actualizá esta fecha manualmente (+30 o +90 días) para que el aviso automático no vuelva a saltar antes de tiempo.', null=True, verbose_name='Próxima revisión de pago'),
        ),
    ]
