# Generated by Django 6.0.6 on 2026-07-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_nutricionista_fecha_aprobacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='transferencia_alias',
            field=models.CharField(blank=True, max_length=100, verbose_name='Alias de transferencia'),
        ),
        migrations.AddField(
            model_name='pais',
            name='transferencia_cvu',
            field=models.CharField(blank=True, max_length=30, verbose_name='CVU / CBU'),
        ),
        migrations.AddField(
            model_name='pais',
            name='transferencia_titular',
            field=models.CharField(blank=True, max_length=150, verbose_name='Titular de la cuenta'),
        ),
    ]
