# Generated by Django 6.0.6 on 2026-07-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pais_transferencia_alias_pais_transferencia_cvu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricionista',
            name='mensaje_recordatorio',
            field=models.TextField(blank=True, help_text='Se manda a cada paciente el día de su turno. Podés usar {nombre}, {hora} y {nutricionista} — se reemplazan solos. Si lo dejás vacío, se usa el mensaje por default.', verbose_name='Mensaje de recordatorio (WhatsApp)'),
        ),
    ]
