# Generated by Django 6.0.6 on 2026-07-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_nutricionista_mensaje_recordatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='portal_debe_cambiar_password',
            field=models.BooleanField(default=True, editable=False, verbose_name='Debe cambiar contraseña del portal'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='portal_password',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
    ]
