# Generated by Django 6.0.6 on 2026-07-11 01:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_backfill_portal_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('porcentaje_descuento', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='% de descuento')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nutricionista_referente', models.ForeignKey(blank=True, help_text='Si un nutricionista te trae clientes con este código, elegilo acá — se le avisa por mail cada uso.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos_descuento', to='core.nutricionista', verbose_name='Nutricionista que lo promociona')),
            ],
            options={
                'verbose_name': 'Código de descuento',
                'verbose_name_plural': 'Códigos de descuento',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='codigo_descuento_usado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos', to='core.codigodescuento', verbose_name='Código de descuento usado'),
        ),
    ]
