# Generated by Django 6.0.6 on 2026-07-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_codigodescuento_nutricionista_codigo_descuento_usado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactointeresado',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='contactointeresado',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre'),
        ),
    ]
