# Generated by Django 6.0.6 on 2026-07-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_poblar_obras_sociales'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricionista',
            name='mp_preapproval_id',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='mp_preference_id_registro',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='pago_registro_confirmado',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
