# Generated by Django 6.0.6 on 2026-07-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_nutricionista_mp_preapproval_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricionista',
            name='mp_ultimo_estado_suscripcion',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
    ]
