# Generated by Django 6.0.6 on 2026-07-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_nutricionista_mp_ultimo_estado_suscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutricionista',
            name='mp_preapproval_id',
        ),
        migrations.RemoveField(
            model_name='nutricionista',
            name='mp_preference_id_registro',
        ),
        migrations.RemoveField(
            model_name='nutricionista',
            name='mp_ultimo_estado_suscripcion',
        ),
        migrations.RemoveField(
            model_name='nutricionista',
            name='pago_registro_confirmado',
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='exento_de_pago',
            field=models.BooleanField(default=False, help_text='Si está tildado, esta cuenta nunca se suspende por falta de pago y no necesita renovar.', verbose_name='Exento de pago (cortesía)'),
        ),
        migrations.CreateModel(
            name='PagoSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses', models.PositiveSmallIntegerField(verbose_name='Meses pagados')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('mp_preference_id', models.CharField(blank=True, editable=False, max_length=100)),
                ('confirmado', models.BooleanField(default=False, editable=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('confirmado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_suscripcion', to='core.nutricionista')),
            ],
            options={
                'verbose_name': 'Pago de suscripción',
                'verbose_name_plural': 'Pagos de suscripción',
                'ordering': ['-creado_en'],
            },
        ),
    ]
