# Generated by Django 6.0.6 on 2026-07-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_nutricionista_mp_preapproval_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutricionista',
            name='frecuencia_pago',
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='proxima_revision_pago',
            field=models.DateField(blank=True, help_text='Se actualiza sola cada vez que se confirma un pago (registro o renovación). A los 5 días de vencida sin pagar, la cuenta se suspende automáticamente.', null=True, verbose_name='Vencimiento de la suscripción'),
        ),
    ]
