# Generated by Django 6.0.6 on 2026-07-12 19:18

import core.models
import core.storage_backends
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_egreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivopaciente',
            name='archivo',
            field=models.FileField(storage=core.storage_backends.storage_archivos_clinicos, upload_to='archivos_pacientes/', validators=[core.models.validar_tamano_archivo, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])], verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, storage=core.storage_backends.storage_archivos_clinicos, upload_to='laboratorios/', validators=[core.models.validar_tamano_archivo, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Archivo PDF'),
        ),
        migrations.AlterField(
            model_name='planalimentario',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, storage=core.storage_backends.storage_archivos_clinicos, upload_to='planes/', validators=[core.models.validar_tamano_archivo, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Plan en PDF'),
        ),
    ]
