# Generated by Django 6.0.6 on 2026-07-12 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_archivopaciente_archivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='mp_link_basico',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='mp_link_basico_trimestral',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='mp_link_premium',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='mp_link_premium_trimestral',
        ),
    ]
