# Generated by Django 6.0.6 on 2026-07-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_pais_mp_link_basico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricionista',
            name='oculto',
            field=models.BooleanField(default=False, help_text='No aparece en el directorio público ni suma en las estadísticas del panel. El dashboard le sigue funcionando normal — es solo para cuentas tuyas de prueba.', verbose_name='Oculto (cuenta interna/de prueba)'),
        ),
    ]
