# Generated by Django 6.0.6 on 2026-07-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_normalizar_dni_pacientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricionista',
            name='mensaje_recordatorio',
            field=models.TextField(blank=True, help_text='Se manda a cada paciente el día de su turno. Podés usar {nombre}, {hora}, {nutricionista} y {link_confirmacion} (un link para que confirme el turno con un toque) — se reemplazan solos. Si lo dejás vacío, se usa el mensaje por default.', verbose_name='Mensaje de recordatorio (WhatsApp)'),
        ),
    ]
