# Generated by Django 6.0.6 on 2026-07-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_nutricionista_mensaje_recordatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricionista',
            name='composicion_corporal',
            field=models.CharField(blank=True, help_text='Separadas por coma. Opciones: isak1, isak2, bioimpedancia', max_length=200, verbose_name='Composición corporal'),
        ),
    ]
