# Generated by Django 6.0.6 on 2026-07-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_nutricionista_composicion_corporal'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricionista',
            name='especialidad_otra',
            field=models.CharField(blank=True, help_text='Se muestra en vez de "Otra" cuando esa opción está tildada en especialidades.', max_length=200, verbose_name='Detalle de "otra" especialidad'),
        ),
    ]
