# Generated by Django 6.0.6 on 2026-07-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_nutricionista_especialidad_otra'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricionista',
            name='fijado_primero',
            field=models.BooleanField(default=False, help_text='Aparece siempre primera en el directorio y en los destacados del home, sin importar el resto de las reglas de orden.', verbose_name='Fijado primero'),
        ),
    ]
