# Generated by Django 6.0.6 on 2026-07-24 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_nutricionista_fijado_primero'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigodescuento',
            name='dias_prueba_gratis',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Si tiene un valor mayor a 0, el registro con este código activa la cuenta Premium gratis por esta cantidad de días, sin pedir pago — se ignora el % de descuento de arriba.', verbose_name='Días de prueba gratis'),
        ),
        migrations.AlterField(
            model_name='codigodescuento',
            name='porcentaje_descuento',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Dejalo en 0 si el código es solo para dar prueba gratis (campo de abajo).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% de descuento'),
        ),
    ]
