# Generated by Django 6.0.6 on 2026-07-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_codigodescuento_dias_prueba_gratis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigodescuento',
            name='dias_prueba_gratis',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Si tiene un valor mayor a 0, el registro con este código activa la cuenta gratis por esta cantidad de días, sin pedir pago — se ignora el % de descuento de arriba. Solo aplica si en el registro eligen el plan Premium (Publicidad + Herramientas); si eligen el plan Básico, este código no da ningún beneficio y paga normal.', verbose_name='Días de prueba gratis'),
        ),
    ]
