# Generated by Django 6.0.6 on 2026-07-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_codigodescuento_dias_prueba_gratis'),
    ]

    operations = [
        migrations.AddField(
            model_name='franjahoraria',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='presencial', help_text='Si en esta franja atendés presencial o por videollamada — se lo mostramos al paciente al reservar.', max_length=10, verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='turno',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], help_text='Presencial o virtual. En los reservados online se completa solo, segun la franja horaria elegida.', max_length=10, verbose_name='Modalidad'),
        ),
    ]
